export const FLAG_CODE: Record<string, string> = {
  'Estados Unidos': 'us',
  'México':         'mx',
  'Canadá':         'ca',
  'Uruguay':        'uy',
  'Panamá':         'pa',
  'Bolivia':        'bo',
  'Ecuador':        'ec',
  'Jamaica':        'jm',
  'Venezuela':      've',
  'Marruecos':      'ma',
  'Bélgica':        'be',
  'Croacia':        'hr',
  'Francia':        'fr',
  'Brasil':         'br',
  'Albania':        'al',
  'Arabia Saudita': 'sa',
  'España':         'es',
  'Argentina':      'ar',
  'Nigeria':        'ng',
  'Nueva Zelanda':  'nz',
  'Inglaterra':     'gb-eng',
  'Portugal':       'pt',
  'Colombia':       'co',
  'Senegal':        'sn',
  'Alemania':       'de',
  'Países Bajos':   'nl',
  'Costa Rica':     'cr',
  'Australia':      'au',
  'Italia':         'it',
  'Chile':          'cl',
  'Camerún':        'cm',
  'Uzbekistán':     'uz',
  'Turquía':        'tr',
  'Japón':          'jp',
  'Ghana':          'gh',
  'Serbia':         'rs',
  'Irán':           'ir',
  'Dinamarca':      'dk',
  'Argelia':        'dz',
  'Honduras':       'hn',
  'Suiza':          'ch',
  'Corea del Sur':  'kr',
  'Túnez':          'tn',
  'Escocia':        'gb-sct',
  'Polonia':        'pl',
  'Austria':        'at',
  'Irak':           'iq',
  'Sudáfrica':      'za',
};
