export const FLAG: Record<string, string> = {
  'Estados Unidos': '🇺🇸',
  'México': '🇲🇽',
  'Canadá': '🇨🇦',
  'Uruguay': '🇺🇾',
  'Panamá': '🇵🇦',
  'Bolivia': '🇧🇴',
  'Ecuador': '🇪🇨',
  'Jamaica': '🇯🇲',
  'Venezuela': '🇻🇪',
  'Marruecos': '🇲🇦',
  'Bélgica': '🇧🇪',
  'Croacia': '🇭🇷',
  'Francia': '🇫🇷',
  'Brasil': '🇧🇷',
  'Albania': '🇦🇱',
  'Arabia Saudita': '🇸🇦',
  'España': '🇪🇸',
  'Argentina': '🇦🇷',
  'Nigeria': '🇳🇬',
  'Nueva Zelanda': '🇳🇿',
  'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Portugal': '🇵🇹',
  'Colombia': '🇨🇴',
  'Senegal': '🇸🇳',
  'Alemania': '🇩🇪',
  'Países Bajos': '🇳🇱',
  'Costa Rica': '🇨🇷',
  'Australia': '🇦🇺',
  'Italia': '🇮🇹',
  'Chile': '🇨🇱',
  'Camerún': '🇨🇲',
  'Uzbekistán': '🇺🇿',
  'Turquía': '🇹🇷',
  'Japón': '🇯🇵',
  'Ghana': '🇬🇭',
  'Serbia': '🇷🇸',
  'Irán': '🇮🇷',
  'Dinamarca': '🇩🇰',
  'Argelia': '🇩🇿',
  'Honduras': '🇭🇳',
  'Suiza': '🇨🇭',
  'Corea del Sur': '🇰🇷',
  'Túnez': '🇹🇳',
  'Escocia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Polonia': '🇵🇱',
  'Austria': '🇦🇹',
  'Irak': '🇮🇶',
  'Sudáfrica': '🇿🇦',
  'Por definir': '🏳️',
};
