// Mapeo de nombres en inglés (football-data.org) → español (nuestra app)
module.exports = {
  'United States': 'Estados Unidos',
  'Mexico': 'México',
  'Canada': 'Canadá',
  'Uruguay': 'Uruguay',
  'Panama': 'Panamá',
  'Bolivia': 'Bolivia',
  'Ecuador': 'Ecuador',
  'Jamaica': 'Jamaica',
  'Venezuela': 'Venezuela',
  'Morocco': 'Marruecos',
  'Belgium': 'Bélgica',
  'Croatia': 'Croacia',
  'France': 'Francia',
  'Brazil': 'Brasil',
  'Albania': 'Albania',
  'Saudi Arabia': 'Arabia Saudita',
  'Spain': 'España',
  'Argentina': 'Argentina',
  'Nigeria': 'Nigeria',
  'New Zealand': 'Nueva Zelanda',
  'England': 'Inglaterra',
  'Portugal': 'Portugal',
  'Colombia': 'Colombia',
  'Senegal': 'Senegal',
  'Germany': 'Alemania',
  'Netherlands': 'Países Bajos',
  'Costa Rica': 'Costa Rica',
  'Australia': 'Australia',
  'Italy': 'Italia',
  'Chile': 'Chile',
  'Cameroon': 'Camerún',
  'Uzbekistan': 'Uzbekistán',
  'Turkey': 'Turquía',
  'Türkiye': 'Turquía',
  'Japan': 'Japón',
  'Ghana': 'Ghana',
  'Serbia': 'Serbia',
  'Iran': 'Irán',
  'IR Iran': 'Irán',
  'Denmark': 'Dinamarca',
  'Algeria': 'Argelia',
  'Honduras': 'Honduras',
  'Switzerland': 'Suiza',
  'Korea Republic': 'Corea del Sur',
  'South Korea': 'Corea del Sur',
  'Tunisia': 'Túnez',
  'Scotland': 'Escocia',
  'Poland': 'Polonia',
  'Austria': 'Austria',
  'Iraq': 'Irak',
  'South Africa': 'Sudáfrica',
};
